### PR TITLE
fix: sponge pad panics on input

### LINKED ISSUE #44: `Rpo256::hash` might panic depending on input size
Currently, `Rpo256::hash` is expecting well-delimited field elements. However, we will panic in case the length isn't evenly divided by the field element length.

The following snippet will cause the panic

```rust
use miden_crypto::hash::rpo::Rpo256;
let message = vec![0_u8; 111];
let message = Rpo256::hash(&message);
```

```
thread 'main' panicked at 'source slice length (6) does not match destination slice length (7)', src/hash/rpo/mod.rs:120:42
```

We should probably pad the bytes with zeroes here

https://github.com/0xPolygonMiden/crypto/blob/3c60484e214f3dad20252267db4d4fcc026fe8b6/src/hash/rpo/mod.rs#L118-L120

Because `chunks`, as opposed to `chunks_exact`, might yield slices with a length smaller than the specified amount of bytes

### PR DESCRIPTION
**Pull request by vlopes11**
closes #44

### CODE REVIEW

File: src/hash/rpo/tests.rs [hunk 1]
```diff
@@ -200,6 +202,18 @@ fn hash_test_vectors() {
     }
 }
 
+#[test]
+fn sponge_bytes_with_remainder_length() {
+    Rpo256::hash(&vec![0_u8; 111]);
+}
```
Comment (grjte) [inline src/hash/rpo/tests.rs:208]: Is this also just testing that it won't panic? Can you add a comment that explains what this test is for?

File: src/hash/rpo/mod.rs [hunk 2]
```diff
@@ -145,6 +138,8 @@ impl Hasher for Rpo256 {
         // we don't need to apply any extra padding because we injected total number of elements
         // in the input list into the capacity portion of the state during initialization.
         if i > 0 {
+            state[RATE_RANGE.start + i..RATE_RANGE.start + RATE_WIDTH - 1].fill(ZERO);
```
Comment (grjte) [inline src/hash/rpo/mod.rs:141]: Why can't we use `RATE_RANGE.start + i..RATE_RANGE.end` here?

File: src/hash/rpo/mod.rs [hunk 3]
```diff
@@ -97,11 +97,7 @@ impl Hasher for Rpo256 {
         // compute the number of elements required to represent the string; we will be processing
         // the string in BINARY_CHUNK_SIZE-byte chunks, thus the number of elements will be equal
         // to the number of such chunks (including a potential partial chunk at the end).
-        let num_elements = if bytes.len() % BINARY_CHUNK_SIZE == 0 {
-            bytes.len() / BINARY_CHUNK_SIZE
-        } else {
-            bytes.len() / BINARY_CHUNK_SIZE + 1
-        };
+        let num_elements = bytes.len() / BINARY_CHUNK_SIZE;
```
Comment (grjte) [inline src/hash/rpo/mod.rs:100]: I'm confused by this and the below comment. I thought the first element of the capacity range is supposed to be either 1 or 0, not the number of elements to be hashed anymore. @Al-Kindi-0?

**Review by grjte — CHANGES_REQUESTED** [review]
Thanks @vlopes11! I left a couple of nits and a question inline

File: src/hash/rpo/tests.rs (hunk 1 above)
Comment (vlopes11) [reply src/hash/rpo/tests.rs]: Indeed, the number 111 is quite "magic" here. Comment added; I also changed the number to a prime so we have the guarantee it won't be divisible.

File: src/hash/rpo/mod.rs (hunk 3 above)
Comment (vlopes11) [reply src/hash/rpo/mod.rs:100]: We have indeed a couple of unanswered questions there. I was thinking of moving the PR to draft until we have these answered.

We indeed  set the first element as the count

https://github.com/0xPolygonMiden/crypto/blob/6de7730e30353c4c889591a52126415ac4819349/src/hash/rpo/mod.rs#L109-L110

But during the first iteration, we override it with the input, as `i` is set as `0`

https://github.com/0xPolygonMiden/crypto/blob/6de7730e30353c4c889591a52126415ac4819349/src/hash/rpo/mod.rs#L116-L136

There is a correct statement below that we don't need to add an extra element with `[1, 0, 0, 0, 0 ,0, 0]` because the number of elements in the initial inputs indeed will differentiate cases with or without remainder chunks.

https://github.com/0xPolygonMiden/crypto/blob/6de7730e30353c4c889591a52126415ac4819349/src/hash/rpo/mod.rs#L143-L149

But, if we change it to be either `0` or `1`, then we have to apply an extra padding element for such cases.

Comment (vlopes11) [reply src/hash/rpo/mod.rs:100]: Another question:

If we apply a montgomery reduction here (as opposed to `Felt::from_mont` that will just take the raw number)
https://github.com/0xPolygonMiden/crypto/blob/6de7730e30353c4c889591a52126415ac4819349/src/hash/rpo/mod.rs#L132-L135

Why do we limit the chunk size to `7` bytes, increasing the permutation count?

https://github.com/0xPolygonMiden/crypto/blob/6de7730e30353c4c889591a52126415ac4819349/src/hash/rpo/mod.rs#L40-L41

File: src/hash/rpo/mod.rs (hunk 2 above)
Comment (vlopes11) [reply src/hash/rpo/mod.rs]: True, fixed!

File: src/hash/rpo/mod.rs (hunk 3 above)
Comment (vlopes11) [reply src/hash/rpo/mod.rs:100]: @Al-Kindi-0 thanks for the clarification. As for the second item, I think its safer to go for 8 bytes with montgomery redcution as the reduction itself should be far cheaper than a permutation - and safer.

Regarding the padding, can you link the latest paper we should use as reference? I'll reproduce in the code the definition we have there.

Comment (Al-Kindi-0) [reply src/hash/rpo/mod.rs:100]: > @Al-Kindi-0 thanks for the clarification. As for the second item, I think its best to go for 8 bytes with montgomery redcution as the reduction itself should be far cheaper than a permutation - and safer. wdyt?
>
 
I am leaning also towards this option but maybe we should benchmark the two approaches to get a better idea.

> Regarding the padding, can you link the latest paper we should use as reference? I'll reproduce in the code the definition we have there.

https://eprint.iacr.org/2022/1577.pdf

Comment (vlopes11) [reply src/hash/rpo/mod.rs:100]: @Al-Kindi-0 it's clear what needs to be done. As pointed by @grjte , capacity will be either one or zero.

The last question I have is about one of the rules in the paper: `2.5 The zero-length input is not allowed`. Why is that? It's not immediately obvious because if we just permutate zeroes, we will also have a valid output (I think). And, considering sponge hashes are usually infallible, I guess we have to come to an output for this case.

**Comment by bobbinth** [comment]
A couple of comments on this:

1. We should use the same padding rule as for `hash_elements()` here. Specifically, if the number of elements to be hashed is a multiple of 8, we set capacity registers to `ZERO`'s. If it is not a multiple of 8, then we set the first capacity register to `ONE` and the rest to `ZERO`'s, and also append `ONE` to the input element string.
2. For binary string, we should keep splitting the input into 7-byte chunks. Splitting it into 8-byte chunks would cause collisions as 8-byte chunks don't map one-to-one to Field elements.
3. We may need to apply additional padding to the last chunk. Specifically, we need to append `1` to the string before converting the last chunk into a field element. I think this is already being done, but I'd probably add a test to make sure something like `[0; 9]` and `[0; 10]` hash to different values.

File: src/hash/rpo/mod.rs [hunk 4]
```diff
@@ -116,18 +112,15 @@ impl Hasher for Rpo256 {
...
-                buf[chunk_len] = 1;
+            // if we are dealing with the last chunk, it may be smaller than BINARY_CHUNK_SIZE
+            // bytes long, so we need to handle it slightly differently. We also append a byte
+            // with value 1 to the end of the string; this pads the string in such a way that
+            // adding trailing zeros results in different hash
+            if chunk.len() < BINARY_CHUNK_SIZE {
+                buf.fill(0);
+                buf[chunk.len()] = 1;
             }
+            buf[..BINARY_CHUNK_SIZE.min(chunk.len())].copy_from_slice(chunk);
```
Comment (bobbinth) [inline src/hash/rpo/mod.rs:123]: nit: I'd probably break up this code into two branches. Maybe something like:
```Rust
if chunk.len() < BINARY_CHUNK_SIZE {
    buf.fill(0);
    buf[chunk.len()] = 1;
    buf[..chunk.len()].copy_from_slice(chunk);
} else {
    buf[..BINARY_CHUNK_SIZE].copy_from_slice(chunk);
}
```
I think this is a bit more readable.

File: src/hash/rpo/mod.rs (hunk 3 above)
Comment (Al-Kindi-0) [reply src/hash/rpo/mod.rs:100]: I think this is was mainly done in order to simplify (thinking about) the new padding rule. Hashing of only zeros is still allowed but the length then is not zero.

File: src/hash/rpo/mod.rs [hunk 5]
```diff
@@ -38,7 +38,7 @@ const DIGEST_SIZE: usize = DIGEST_RANGE.end - DIGEST_RANGE.start;
 const NUM_ROUNDS: usize = 7;
 
 /// The number of byte chunks defining a field element when hashing a sequence of bytes
-const BINARY_CHUNK_SIZE: usize = 7;
+const BINARY_CHUNK_SIZE: usize = 8;
```
Comment (bobbinth) [inline src/hash/rpo/mod.rs:41]: Wouldn't this lead to collisions? (I mentioned this in https://github.com/0xPolygonMiden/crypto/pull/46#issuecomment-1406172233). For example, wouldn't 0 and 2^64 - 2^32 + 1 hash to the same value?

Comment (vlopes11) [reply src/hash/rpo/mod.rs]: Yes, the modulus indeed would cause a collision there. I updated the tests to check for that case + added a collision search for 0..255 zeroes hashed.

File: src/hash/rpo/mod.rs [hunk 6]
```diff
@@ -94,61 +94,65 @@ impl Hasher for Rpo256 {
...
         // in the input list into the capacity portion of the state during initialization.
-        if i > 0 {
+        if i != 0 {
+            state[RATE_RANGE.start + i..RATE_RANGE.end].fill(ZERO);
+            state[RATE_RANGE.start + i] = ONE;
             Self::apply_permutation(&mut state);
         }
 
-        // return the first 4 elements of the state as hash result
+        // return the first 4 elements of the state as hash result.
```
Comment (bobbinth) [inline src/hash/rpo/mod.rs:155]: nit: I know this is an old comment but I think it is incorrect. We are returning the first 4 elements of the rate rather than the state.

File: src/hash/rpo/mod.rs [hunk 7]
```diff
@@ -94,61 +94,65 @@ impl Hasher for Rpo256 {
...
-            // convert the bytes into a field element and absorb it into the rate portion of the
-            // state; if the rate is filled up, apply the Rescue permutation and start absorbing
-            // again from zero index.
-            state[RATE_RANGE.start + i] = Felt::new(u64::from_le_bytes(buf));
-            i += 1;
-            if i % RATE_WIDTH == 0 {
+            // set the current rate element to the input. since we take 7 bytes, we don't need to
+            // worry about the element not being canonical as it will always fit the field. this
+            // way, we can assume this is already a reduced number.
+            state[RATE_RANGE.start + i] = Felt::from_mont(u64::from_le_bytes(buf));
```
Comment (bobbinth) [inline src/hash/rpo/mod.rs:133]: I would actually keep this as `Felt::new(u64::from_le_bytes(buf))`. The main reason is that if we'd need to implement hashing of binary strings inside the VM, handling this conversion would add quite a bit of complexity (the VM sees elements in canonical form).

**Review by bobbinth — CHANGES_REQUESTED** [review]
Looks good! Thank you! I left a couple small comments inline.

File: src/hash/rpo/mod.rs (hunk 6 above)
Comment (vlopes11) [reply src/hash/rpo/mod.rs]: True, fixed!

File: src/hash/rpo/mod.rs (hunk 7 above)
Comment (vlopes11) [reply src/hash/rpo/mod.rs]: I initially thought they would be canonical after the permutation, considering a couple of additions and multiplications are performed. But better safe than sorry, fixed!

File: src/hash/rpo/mod.rs [hunk 8]
```diff
@@ -94,61 +94,65 @@ impl Hasher for Rpo256 {
...
+                buf[..chunk.len()].copy_from_slice(chunk);
+                buf[chunk.len()] = 1;
             }
 
-            // convert the bytes into a field element and absorb it into the rate portion of the
-            // state; if the rate is filled up, apply the Rescue permutation and start absorbing
-            // again from zero index.
+            // set the current rate element to the input. since we take 7 bytes, we don't need to
+            // worry about the element not being canonical as it will always fit the field. this
+            // way, we can assume this is already a reduced number.
```
Comment (bobbinth) [inline src/hash/rpo/mod.rs:132]: I think this comment needs to be updated.

Comment (bobbinth) [reply src/hash/rpo/mod.rs]: I think it is better - but I still find the reference to "canonical" a bit confusing. Maybe change it to something like "... since we take at most 7 bytes, we are guaranteed that the input data will fit into a single field element".?

Comment (vlopes11) [reply src/hash/rpo/mod.rs]: That makes sense; fixed

File: src/hash/rpo/mod.rs [hunk 9]
```diff
@@ -94,61 +94,64 @@ impl Hasher for Rpo256 {
...
             }
-        }
+        });
 
         // if we absorbed some elements but didn't apply a permutation to them (would happen when
         // the number of elements is not a multiple of RATE_WIDTH), apply the RPO permutation.
         // we don't need to apply any extra padding because we injected total number of elements
         // in the input list into the capacity portion of the state during initialization.
-        if i > 0 {
+        if i != 0 {
```
Comment (bobbinth) [inline src/hash/rpo/mod.rs:148]: I think the comments above this line are outdated.

Comment (vlopes11) [reply src/hash/rpo/mod.rs:148]: IIUC it was the `total` mention. Fixed!

Comment (bobbinth) [reply src/hash/rpo/mod.rs:148]: Thank you! I would probably make it a bit more precise and state the the flag goes into the first capacity element. For example, something like this:
```
we don't need to apply any extra padding because the first capacity element contains
a flag indicating whether the input is evenly divisible by the rate.
```

Comment (vlopes11) [reply src/hash/rpo/mod.rs:148]: That makes sense, fixed!

**Review by bobbinth — APPROVED** [review]
All looks good! Thank you!

**Review by grjte — APPROVED** [review]
Looks good, thank you!
